# Generated by Django 4.2.4 on 2024-01-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_products_image_alter_rating_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user_id',
            new_name='customer',
        ),
    ]
