# Generated by Django 4.2.4 on 2024-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_prices_date_offer_prices_date_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='register_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
