# Generated by Django 4.2.4 on 2024-01-17 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_customer_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_rated_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='store.customer'),
        ),
        migrations.AddField(
            model_name='rating',
            name='customer_rated',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_rated', to='store.customer'),
        ),
    ]
