# Generated by Django 4.2.4 on 2024-01-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_rating_user_id_remove_rating_user_rated_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_content',
            field=models.BinaryField(blank=True, default=b'', null=True),
        ),
    ]
