# Generated by Django 5.0.1 on 2024-01-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_message_content_message_encrypted_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='date_offer',
        ),
        migrations.AddField(
            model_name='prices',
            name='timestamp',
            field=models.IntegerField(default=1706260334.156883),
        ),
        migrations.AddField(
            model_name='products',
            name='timestamp',
            field=models.IntegerField(default=1706260334.1488826),
        ),
    ]
