# Generated by Django 5.0.1 on 2024-02-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_customer_timestamp_alter_prices_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='timestamp',
            field=models.IntegerField(default=1707318286.2863274),
        ),
        migrations.AlterField(
            model_name='prices',
            name='timestamp',
            field=models.IntegerField(default=1707318286.2863274),
        ),
        migrations.AlterField(
            model_name='prices',
            name='timestamp_status',
            field=models.IntegerField(blank=True, default=1707318286.2863274, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='timestamp',
            field=models.IntegerField(default=1707318286.2863274),
        ),
        migrations.AlterField(
            model_name='rating',
            name='timestamp',
            field=models.IntegerField(default=1707318286.2863274),
        ),
    ]
